### ISSUE TITLE
Using Custom Dataset with Different Input Lengths for Model

### ISSUE THREAD

**Issue by rozhix** [ServiceNow/tactis#33]
My input dimensions are [1500, 50, 6] and my label dimensions are [1500, 1]. Can I use this model? If so, could you please explain how to configure it correctly?

**Comment by marcotet** [comment]
Hi rozhix, could you tell me a little more about what your input and label represent in your example?

TACTiS has been designed for mostly multivariate timeseries forecasting problems, where the input and output both share two dimensions (the batch dimension and the number of variables dimension), which does not match with the example you gave me.

**Comment by rozhix** [comment]
I am working on a battery dataset that contains numerous discharge process files. Each file includes six features that represent the discharging process. At the end of the discharging process, the capacity of the battery is reported. My goal is to predict the battery's capacity based on the discharging process data.

The dataset consists of six time series for each discharge process, with the time series having approximately 100 time steps, ranging from t0 to t99. However, the length of the time series is not fixed and may vary in each file. Therefore, the input data for my prediction model is composed of these six time series, and the output label is the corresponding battery capacity. I would like to know if I can use the TACTiS model?

**Comment by marcotet** [comment]
Sadly, this kind of problem wouldn't work with TACTiS. TACTiS assumes that both your input (the discharging process in your case) and the output (the battery capacity) comes from the same underlying process.
I don't have an alternative suggestion in mind, but I would suggest that you look for models whose aim is to learn an embedding from a time series. You are likely to be able to get from these embeddings to your desired output by adding an extra layer to such a model.

Good luck with your research!
